name: calendar_picker
description: A lightweight, customizable date picker package for Flutter that supports              
  - ðŸ—“ï¸ **Gregorian Calendar**
  - ðŸŒ™ **Hijri  Calendar**
  - ðŸ—¿ **Ethiopian Calendar**
version: 2.0.0
homepage: https://github.com/HalidAwell/calendar_picker
repository: https://github.com/HalidAwell/calendar_picker
issue_tracker: https://github.com/HalidAwell/calendar_picker/issues

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  ethiopian_datetime: ^1.0.3
  hijri: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0 # Optional: for linting best practices

flutter:
  uses-material-design: true
